### ISSUE TITLE
[feat] FileManager

### ISSUE THREAD

**Issue by Judy-999** [Judy-999/ios-wanted-GyroData#16]
## Description
FileManager 구현

## Todo
- [x] FileManager를 통해 저장하기
- [x] FileManager를 통해 불러오기
- [x] FileManager를 통해 삭제하기
