### ISSUE TITLE
[feat] MeasurementScene 

### ISSUE THREAD

**Issue by llghdud921** [Judy-999/ios-wanted-GyroData#2]
## Description
측정화면 구현

## Todo
- [x] SegmentControl 구현
- [x] 측정 Button 구현
- [x] 정지 Button 구현
- [x] 그래프 뷰 표현
- [x] NavigationBarButton 구현
- [x] NavigationBar Title 설정
