### ISSUE TITLE
[Setting] 프로젝트 기본 설정

### ISSUE THREAD

**Issue by llghdud921** [Judy-999/ios-wanted-GyroData#3]
## Description
프로젝트 첫화면 설정

## Todo
- [x] Storyboard 파일 삭제
- [x] SceneDelegate 수정
- [x] info.plist 수정
- [x] Deployment target 15.5로 수정
- [x] Xcode compatibilityVersion, BuildIndependentTargetsInParallel version 변경
